### ISSUE TITLE
Capacitor 3 Support

### ISSUE THREAD

**Issue by thomasvidas** [openforge/capacitor-game-services#24]
This plugin doesn't support Capacitor 3. It should be a pretty straightforward process to upgrade. The upgrade guide here: https://capacitorjs.com/docs/updating/plugins/3-0#use-the-new-capacitorplugin-annotation

Happy to contribute a PR to help migrate it over from the Capacitor 2.x style to Capacitor 3.x. 😄

**Comment by crowbait** [comment]
I don't think openforge works on this anymore. Maybe if you'd fork it and migrate it?

**Comment by jedihacks** [comment]
Sorry for the delay @thomasvidas - we just updated to Capacitor v4 so hope that helps!

**Comment by arbassic** [comment]
Will you put an updated version on npm as a release?
